apiVersion: apps/v1
kind: Deployment
metadata:
  name: mscv-cursos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mscv-cursos
  template:
    metadata:
      labels:
        app: mscv-cursos
    spec:
      containers:
      - image: joshua1704/msvc-cursos:latest
        name: mscv-cursos
        ports:
        - containerPort: 8002
        env:  # Move env under the container
        - name: PORT
          value: "8002"
        - name: DB_HOST
          value: "postgres14:5432"
        - name: DB_DATABASE
          value: "msvc_cursos"
        - name: DB_USERNAME
          value: "postgres"
        - name: DB_PASSWORD
          value: "Haikyuu1212"
        - name: USUARIOS_URL
          value: "mscv-usuarios:8001"
        volumeMounts:
          - name: data-mysql
            mountPath: /var/lib/mysql  
      volumes:
        - name: data-mysql
          hostPath: 
            path: /var/lib/mysql
            type: DirectoryOrCreate