#version: "3.9" solo para docker v1

services:
  
  mysql8:
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Haikyuu1212
      MYSQL_DATABASE: msvc_usuarios
    volumes:
      - data-mysql:/var/lib/mysql
    restart: always
    networks:
      - spring

  postgres14:
    image: postgres:14-alpine
    ports:
      - "5532:5432"
    environment:
      POSTGRES_PASSWORD: Haikyuu1212
      POSTGRES_DB: msvc_cursos
    volumes:
      - data-postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - spring    

  msvc-usuarios:
    container_name: msvc-usuarios
    image: joshua1704/msvc-usuarios
    #build:
     # context: ./msvc-usuarios
      #dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      DB_HOST: mysql8:3306
      DB_DATABASE: msvc_usuarios
      CURSOS_URL: msvc-cursos:8002
    networks:
      - spring
    depends_on:
      - mysql8
    restart: always

  msvc-cursos:
    container_name: msvc-cursos
    image: joshua1704/msvc-cursos
 #   build:
  #    context: ./msvc-cursos
   #   dockerfile: Dockerfile
    ports:
      - "8002:8002"
    environment:
      DB_HOST: postgres14:5432
      DB_DATABASE: msvc_cursos
      USUARIOS_URL: msvc-usuarios:8001

    networks:
      - spring
    depends_on:
      - postgres14
      - msvc-usuarios
    restart: always

volumes:
  data-mysql:
    external: true
  data-postgres:
    external: true

networks:
  spring:
    driver: bridge
