apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  volumeName: postgres-pv
  accessModes:
    - ReadWriteOnce
  storageClassName: standar  
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem

