#version: "3.9" solo para docker v1

services:
  
  mysql8:
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Haikyuu1212
      MYSQL_DATABASE: msvc_usuarios
    volumes:
      - data-mysql:/var/lib/mysql
    restart: always
    networks:
      - spring

  
  msvc-usuarios:
    container_name: msvc-usuarios
    image: joshua1704/msvc-usuarios
    #build:
     # context: ./msvc-usuarios
      #dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      DB_HOST: mysql8:3306
      DB_DATABASE: msvc_usuarios
      CURSOS_URL: ec2-3-89-226-1.compute-1.amazonaws.com:8002
    networks:
      - spring
    depends_on:
      - mysql8
    restart: always

  


volumes:
  data-mysql:
    external: true
  
networks:
  spring:
    driver: bridge
