#version: "3.9" solo para docker v1

services:
  
  postgres14:
    image: postgres:14-alpine
    ports:
      - "5532:5432"
    environment:
      POSTGRES_PASSWORD: Haikyuu1212
      POSTGRES_DB: msvc_cursos
    volumes:
      - data-postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - spring    

  msvc-cursos:
    container_name: msvc-cursos
    image: joshua1704/msvc-cursos
 #   build:
  #    context: ./msvc-cursos
   #   dockerfile: Dockerfile
    ports:
      - "8002:8002"
    environment:
      DB_HOST: postgres14:5432
      DB_DATABASE: msvc_cursos
      USUARIOS_URL: ec2-3-84-24-155.compute-1.amazonaws.com:8001

    networks:
      - spring
    depends_on:
      - postgres14
      - msvc-usuarios
    restart: always

volumes:
  data-postgres:
    external: true

networks:
  spring:
    driver: bridge
